version: '3.9'

name: nomad_foods_rag_streamlit_app


services:
  chatbot_app:
    image: ziedtrikimlops/rag-chatbot-nomad-food:v1
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=feedback_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_password
    depends_on:
      - postgres
    ports:
      - "8501:8501"

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=feedback_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - postgres

volumes:
  postgres_data: