apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-nomad-streamlit-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-nomad-streamlit-chatbot
  template:
    metadata:
      labels:
        app: rag-nomad-streamlit-chatbot
    spec:
      containers:
      - name: rag-nomad-streamlit-chatbot
        image: ziedtrikimlops/rag-chatbot-nomad-food:v1
        ports:
        - containerPort: 8501
        env:
        - name: MISTRAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: mistral-api-key
              key: MISTRAL_API_KEY
