apiVersion: v1
kind: Service
metadata:
  name: rag-nomad-streamlit-service
spec:
  selector:
    app: rag-nomad-streamlit-chatbot
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
    nodePort: 30001
  type: NodePort