apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-chatbot
  template:
    metadata:
      labels:
        app: streamlit-chatbot
    spec:
      containers:
      - name: streamlit-chatbot
        image: ziedtrikimlops/rag-chatbot-fintech:v3
        ports:
        - containerPort: 8501
        env:
        - name: ELASTICSEARCH_HOST
          value: "http://elasticsearch-service:9200"
        - name: MISTRAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: mistral-api-key
              key: MISTRAL_API_KEY