apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: streamlit-chatbot
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
    nodePort: 30000
  type: NodePort