{
 "title": "RAG-Nomad_Foods_Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average Response time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(response_time) AS avg_response_time\r\nFROM feedback;\r\n"
    }
   ]
  },
  {
   "title": "LLM Model Used",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT model_used, COUNT(*) AS count\r\nFROM feedback\r\nGROUP BY model_used;\r\n"
    }
   ]
  },
  {
   "title": "Total Feedback Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_feedback_count\r\nFROM feedback;\r\n"
    }
   ]
  },
  {
   "title": "Answer Relevancy Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(CASE WHEN relevant THEN 1 END) AS relevant_count,\r\n       COUNT(CASE WHEN NOT relevant THEN 1 END) AS not_relevant_count\r\nFROM feedback;\r\n"
    }
   ]
  },
  {
   "title": "Count of Different Answers",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(CASE WHEN thumbs_up THEN 1 END) AS thumbs_up_count,\r\n       COUNT(CASE WHEN thumbs_down THEN 1 END) AS thumbs_down_count\r\nFROM feedback;\r\n"
    }
   ]
  }
 ]
}